### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by Dasonk** [r-lib/backports#11]
I saw this package on my system today and it actually reminded me of some code I wrote a while ago.  It looks like I wanted to implement something very similar to this previously.

https://github.com/Dasonk/future

I had backports for 2.14, 2.15 and 3.0 although I think the 3.0 was incomplete.

https://github.com/Dasonk/future2.14
https://github.com/Dasonk/future2.15
https://github.com/Dasonk/future3.0

**Comment by mllg** [comment]
Closing here, this package is not going to implement more backports for these R versions.
