### ISSUE TITLE
Can we apply GPLv3 license to source codes which utilize backports?

### ISSUE THREAD

**Issue by YTs63** [r-lib/backports#21]
We are currently developing an application using R language and in that application, we use OSS libraries under GPLv3 (e.g. Matrix, tidyselect). 
During the development, we noticed that some of OSS libraries depends on backports.
Is it possible to apply GPLv3 to our application?
I found that rprojroot which imports backports is published under GPLv3.

**Comment by mllg** [comment]
I've changed to license to GPL-2 | GPL-3 in 459ebc0abb3b97f5e61e926adec643445cd96b35.
