### ISSUE TITLE
q argument of sQuote() and dQuote()

### ISSUE THREAD

**Issue by jennybc** [r-lib/backports#24]
I recently ran into this backwards compatibility problem.

`sQuote()` and `dQuote()` gained the explicit `q` argument in R 3.6.0.

https://github.com/wch/r-source/blob/2c65d3d6bf25af0a3078639604feb280e69e1e46/doc/NEWS.Rd#L727-L729

> `sQuote()` and `dQuote()` get an explicit `q` argument with obvious default instead of using `getOption("fancyQuotes")` implicitly and unconditionally.

**Comment by mllg** [comment]
Fixed in cc4846ec66b35c947572ff79bc457c332fb37d7d.
