### ISSUE TITLE
CRAN windows binary issue

### ISSUE THREAD

**Issue by jasonelaw** [r-lib/backports#33]
There is no backports 1.1.7 binary on CRAN for windows. It looks like there was an error in the CRAN build process: https://www.r-project.org/nosvn/R.check/r-release-windows-ix86+x86_64/backports-00check.html. Other than installing from source, is there another solution?

**Comment by mllg** [comment]
I've contacted CRAN about it and I expect it to be resolved in the next ~48 hours.

I don't think that there is another solution than building from source.

**Comment by mllg** [comment]
Binary is now served via CRAN.
