### ISSUE TITLE
implement tools::vignetteInfo

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/backports#35]
Was released in R 3.6.0 (https://stat.ethz.ch/pipermail/r-announce/2019/000641.html). And of particular relevance for vignette building seems now to fail for R < 3.6 in R CMD check because this function is not available: https://travis-ci.org/github/r-lib/styler/builds/693410966 and https://travis-ci.org/github/r-lib/styler/jobs/693410971#L1186

**Comment by schloerke** [comment]
Just to connect related issues... https://github.com/rstudio/rmarkdown/issues/1831

**Comment by mllg** [comment]
Looks like vignetteInfo has been in package `tools` for some years now. #36 just re-exports it.
