### ISSUE TITLE
backports not installing correctly?

### ISSUE THREAD

**Issue by ngreifer** [r-lib/backports#37]
Hello. I import `backports` in my R package `cobalt` ([CRAN link](https://CRAN.R-project.org/package=cobalt)). I require the latest version (1.1.7). However, I've had several users complain that they see the error 

`Error in deparse1(substitute(x)) : could not find function "deparse1"`

I have the following line in my package code:

```
.onLoad <- function(libname, pkgname) {
  backports::import(pkgname)
}
```

I feel that when users install `cobalt`, `backports` isn't being installed or updated to the latest version. I've told my users to manually install `backports` or update their version of R. Do you know what's going on? Thanks.

**Comment by mllg** [comment]
Thanks for the report. The import was bugged in v1.1.7. I've just uploaded a fixed release to CRAN.
The issue of your users should disappear after they update backports. Additionally, `cobalt` should depend on v1.1.8 as soon as backports has hit the CRAN mirrors.
