### ISSUE TITLE
backports doesn't export `str2expression`?

### ISSUE THREAD

**Issue by ngreifer** [r-lib/backports#39]
It came to my attention that `backports` does not export all functions from previous R releases, including `str2expression` (and the related `str2lang`). If this was deliberate, is there a reason for it? Thanks.

**Comment by dmurdoch** [comment]
I'd guess it's just that nobody has submitted them.  It should be a really easy PR, since the current R source gives R equivalents (though it actually uses C based internals).  See https://github.com/wch/r-source/blob/cd1d256fb2f288af67b3d51b1ee44e97064c285f/src/library/base/R/parse.R#L60 .
