### ISSUE TITLE
Install issue with version 1.1.8

### ISSUE THREAD

**Issue by rsmiller74** [r-lib/backports#43]
I have tried several ways to install the package but all fail in the same way with Error 127.

> packageurl <- "https://cran.r-project.org/src/contrib/backports_1.1.8.tar.gz"
> install.packages(packageurl, repos=NULL, dependencies=TRUE, verbose=TRUE, type="source")
trying URL 'https://cran.r-project.org/src/contrib/backports_1.1.8.tar.gz'
Content type 'application/x-gzip' length 18047 bytes (17 KB)
downloaded 17 KB

system (cmd0): C:/Users/APRMIL~1/DOCUME~1/R/R-40~1.2/bin/x64/R CMD INSTALL
* installing *source* package 'backports' ...
** package 'backports' successfully unpacked and MD5 sums checked
** using staged installation
** libs

*** arch - i386
"c:/rtools40/mingw32/bin/"gcc  -I"C:/Users/APRMIL~1/DOCUME~1/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c dotsElt.c -o dotsElt.o
c:/rtools40/mingw32/bin/gcc: not found
make: *** [dotsElt.o] Error 127
ERROR: compilation failed for package 'backports'
* removing 'C:/Users/aprmiller/Documents/R/R-4.0.2/library/backports'
Warning in install.packages :
  installation of package ‘C:/Users/APRMIL~1/AppData/Local/Temp/1/RtmpqC25J1/downloaded_packages/backports_1.1.8.tar.gz’ had non-zero exit status

**Comment by rsmiller74** [comment]
this appears to be preventing the installation of several packages that rely on backports.

**Comment by rsmiller74** [comment]
this appears to be preventing the installation of several packages that rely on backports.

**Comment by rsmiller74** [comment]
this appears to be preventing the installation of several packages that rely on backports.

**Comment by rsmiller74** [comment]
this appears to be preventing the installation of several packages that rely on backports.

**Comment by rsmiller74** [comment]
this appears to be preventing the installation of several packages that rely on backports.

**Comment by rsmiller74** [comment]
this appears to be preventing the installation of several packages that rely on backports.

**Comment by rsmiller74** [comment]
this appears to be preventing the installation of several packages that rely on backports.

**Comment by rsmiller74** [comment]
this appears to be preventing the installation of several packages that rely on backports.

**Comment by rsmiller74** [comment]
this appears to be preventing the installation of several packages that rely on backports.

**Comment by rsmiller74** [comment]
this appears to be preventing the installation of several packages that rely on backports.

**Comment by mllg** [comment]
You are trying to install from source (`type="source"`), but don't seem to have Rtools properly configured. Error 127 means "file not found", and the file in question is the C compiler. 

Re-install Rtools or install the binary package provided by CRAN:
```r
install.packages("backports")
```
