### ISSUE TITLE
backports not built for Windows release and oldrel after 1.1.7

### ISSUE THREAD

**Issue by ngreifer** [r-lib/backports#44]
I'm not sure if this is actually consequential or how much control you have over it, but it looks like CRAN can't build the newer versions of `backports` for r-release and r-oldrel for Windows, which is causing packages (e.g., mine, `cobalt`) that import it to also fail to be built for those versions. I'm worried the CRAN team is going to come knocking at my door to tell me to fix these issues or they'll take my package down.

**Comment by mllg** [comment]
I've contacted CRAN, Uwe is triggering a rebuild for backports. Thanks for reporting, I haven't noticed that no binaries were build.
