### ISSUE TITLE
README.md: Make available on CRAN

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/backports#57]
# Issue

The CRAN package page <https://cran.r-project.org/package=backports> has no instructions on how to use **backports**.  A package developer will look for either a vignette or a README, but there's nothing.

# Suggestion

Remove 

https://github.com/r-lib/backports/blob/05e1381c6c348afa9b1edb52ed605c2e375b8864/.Rbuildignore#L1

so that the README.md file is bundled with the tarball, so that it ends up on CRAN.

**Comment by mllg** [comment]
Thanks!
