### ISSUE TITLE
Add null coalescing operator `%||%` to be introduced with R 4.4.0

### ISSUE THREAD

**Issue by realHenningLorenzen** [r-lib/backports#80]
#### Reference

<https://cloud.r-project.org/bin/windows/base/NEWS.R-4.4.0rc.html>

> `L %||% R` newly in **base** is an expressive idiom for the phrases `if(!is.null(L)) L else R or if(is.null(L)) R else L`.

**Comment by olivroy** [comment]
there is also `sort_by()`
